on:
  push:
    branches:
      - main

jobs:
  ci_trigger:
    runs-on: ubuntu-latest
    name: Purge changed files from cache 
    steps:
      - name: Trigger
        id: trigger
        uses: adobe-rnd/github-purge-cache-action@master
        with:
          helix-url: https://spark-website--adobe.hlx.live/
          repo-token: ${{ secrets.GITHUB_TOKEN }}
